### ISSUE TITLE
スーパバイザの"会話を聞く"が反応しない

### ISSUE THREAD

**Issue by ymteruya** [twilioforkwc/twilio-taskrouter-contact-center#2]
未実装

**Comment by twilioforkwc** [comment]
対応済
commit: [f1c095277e5871fee0c4b5bc6e6551fc17194ac8](https://github.com/twilioforkwc/twilio-taskrouter-contact-center/commit/f1c095277e5871fee0c4b5bc6e6551fc17194ac8)
