### ISSUE TITLE
TaskのStatusが"wrapping"になりRoutingされない

### ISSUE THREAD

**Issue by ymteruya** [twilioforkwc/twilio-taskrouter-contact-center#4]
Taskのステータスがcompletedにならずwrappingになる。
そうなるとworkerがidle状態でもroutingされない。

**Comment by twilioforkwc** [comment]
対応済
commit: [647e3b377bbfaa4817f6828fc6c48d087e3f18e9](https://github.com/twilioforkwc/twilio-taskrouter-contact-center/commit/647e3b377bbfaa4817f6828fc6c48d087e3f18e9)
