### ISSUE TITLE
WorkflowのEdit画面で情報が表示されないことがある

### ISSUE THREAD

**Issue by ymteruya** [twilioforkwc/twilio-taskrouter-contact-center#5]
Workflowのプロパティ「filter」が何も登録されていない場合、Workflow全体の情報が表示されない。

**Comment by twilioforkwc** [comment]
対応済
commit: [4c59d28e523bbe97e45d2f5dc19c13553f292841](https://github.com/twilioforkwc/twilio-taskrouter-contact-center/commit/4c59d28e523bbe97e45d2f5dc19c13553f292841)
